### ISSUE TITLE
Blog section (description) are not clear.

### ISSUE THREAD

**Issue by Chimpkiller** [Venom100sam/Tour-And-Travel-Management-System#11]
![image](https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/120244563/1cd308aa-d705-497a-a686-fb71e19cb1be)

**Comment by ShakyaSujal** [comment]
Solved
<img width="506" alt="image" src="https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/119122806/49e477d6-aa57-4cfd-be5c-52382a83061d">
