### ISSUE TITLE
footer background

### ISSUE THREAD

**Issue by Chimpkiller** [Venom100sam/Tour-And-Travel-Management-System#4]
![image](https://user-images.githubusercontent.com/120244563/236653791-c07ed022-1a8d-46bb-86e4-572ca384fee1.png)

Fix footer background

**Comment by NirjalKasaa** [comment]
![image](https://user-images.githubusercontent.com/114579879/236655094-7f19594d-199a-4f0d-87b8-cf9be0c20a10.png)

Footer background fixed for Discover, Quick Links and Contact.
