### ISSUE TITLE
Destination not working

### ISSUE THREAD

**Issue by Chimpkiller** [Venom100sam/Tour-And-Travel-Management-System#5]
![image](https://user-images.githubusercontent.com/120244563/236653855-1907860b-bb7d-4950-873e-f8604842e7c7.png)

Destination on the navigation bar is not working

**Comment by NirjalKasaa** [comment]
The Destination was not intended to be there, I've removed it.
Here is what the updated navigation bar looks like.

![image](https://user-images.githubusercontent.com/114579879/236655182-00d540e0-9ebb-4286-9f94-9014cdbd8dd1.png)
