### ISSUE TITLE
Contact us page contacts are not being displayed

### ISSUE THREAD

**Issue by Chimpkiller** [Venom100sam/Tour-And-Travel-Management-System#6]
<img width="280" alt="image" src="https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/120244563/9801db3c-11df-4d2a-98da-ccf42be58199">

**Comment by ShakyaSujal** [comment]
Solved

**Comment by ShakyaSujal** [comment]
<img width="468" alt="image" src="https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/119122806/3e60964f-8354-4427-8594-8b294634a1a6">
