### ISSUE TITLE
Information of the team are not being displayed on about us page

### ISSUE THREAD

**Issue by Chimpkiller** [Venom100sam/Tour-And-Travel-Management-System#8]
<img width="264" alt="image" src="https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/120244563/d49aff9c-1400-4888-b3ce-9954c6551640">

**Comment by ShakyaSujal** [comment]
Solved
<img width="417" alt="image" src="https://github.com/Venom100sam/Tour-And-Travel-Management-System/assets/119122806/35cb5e0a-ee96-4c4d-9764-2b5e87de5bf4">
